[project]
name = "dataextract"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.5",
    "pandas-stubs>=2.3.2.250926",
    "seaborn>=0.13.2",
    "types-seaborn>=0.13.2.20250914",
]
